export const UPDATE_BANNER_INFO = "UPDATE_BANNER_INFO";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAILED = "UPDATE_BANNER_FAILED";
export const UPDATE_BANNER_RESET = "UPDATE_BANNER_RESET";

export const GET_BANNER_INFO = "GET_BANNER_INFO";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILED = "GET_BANNER_FAILED";
export const GET_BANNER_RESET = "GET_BANNER_RESET";

export const GET_BANNER_DETAIL_INFO = "GET_BANNER_DETAIL_INFO";
export const GET_BANNER_DETAIL_SUCCESS = "GET_BANNER_DETAIL_SUCCESS";
export const GET_BANNER_DETAIL_FAILED = "GET_BANNER_DETAIL_FAILED";
export const GET_BANNER_DETAIL_RESET = "GET_BANNER_DETAIL_RESET";
