export const UPDATE_BANNER_INFO = "UPDATE_BANNER_INFO";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_FAILED = "UPDATE_BANNER_FAILED";
export const UPDATE_BANNER_RESET = "UPDATE_BANNER_RESET";
