export const BRANCH_CREATE_REQUEST = "BRANCH_CREATE_REQUEST";
export const BRANCH_CREATE_SUCCESS = "BRANCH_CREATE_SUCCESS";
export const BRANCH_CREATE_FAIL = "BRANCH_CREATE_FAIL";
export const BRANCH_CREATE_RESET = "BRANCH_CREATE_RESET";

export const BRANCH_UPDATE_REQUEST = "BRANCH_UPDATE_REQUEST";
export const BRANCH_UPDATE_SUCCESS = "BRANCH_UPDATE_SUCCESS";
export const BRANCH_UPDATE_FAIL = "BRANCH_UPDATE_FAIL";
export const BRANCH_UPDATE_RESET = "BRANCH_UPDATE_RESET";
