export const CREATE_CATEGORY_INFO = "CREATE_CATEGORY_INFO";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED";
export const CREATE_CATEGORY_RESET = "CREATE_CATEGORY_RESET";

export const UPDATE_CATEGORY_INFO = "UPDATE_CATEGORY_INFO";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const GET_CATEGORY_INFO = "GET_CATEGORY_INFO";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";
export const GET_CATEGORY_RESET = "GET_CATEGORY_RESET";

export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";


